### ISSUE TITLE
support environment with custom install dirs

### ISSUE THREAD

**Issue by slorquet** [radare/bokken#1]
hello

I have installed radare2 in my own dir, and bokken does not start because it does not find the radare2 libs. the reason is that LD_LIBRARY_PATH is overwritten. The following patch fixes this kind of setup:

```
diff --git a/bokken b/bokken
index cdaaf38..dc5b9d1 100755
--- a/bokken
+++ b/bokken
@@ -10,5 +10,5 @@ if [ "$PYTHON_VER" -eq 3 ];then
 fi

 # distorm in bokken+pyew mode needs this for now.
-export LD_LIBRARY_PATH=$BOKKEN_DIR/lib
+export LD_LIBRARY_PATH=$BOKKEN_DIR/lib:$LD_LIBRARY_PATH
 $PYTHON_EXECUTABLE $BOKKEN_DIR/bokken.py $@
```

**Comment by radare** [comment]
looks good to me, can you send a pullreq or just edit the file in github webui?

**Comment by slorquet** [comment]
done, https://github.com/radare/bokken/pull/2

**Comment by radare** [comment]
The real bokken repo is in https://github.com/inguma/bokken
