### ISSUE TITLE
r2.r_core ImportError: dynamic module does not define init function (initr_core)

### ISSUE THREAD

**Issue by nohope91** [radare/bokken#6]
Hello Sir @radare I just want to thank you for all your efforts with me setting up r2 & r2-bindings
Now everything seems working perfectly, but one last thing to go : 

root@kali:~/Downloads/bokken-master# ./bokken
	Python version... 	OK
Checking:
	Pyew availability... 	OK
	Radare availability... 	OK
	GTK UI dependencies... 	OK
	GtkSourceView2... 	OK
	Psyco availability... 	D'oh!
No psyco module found. It's recomended to use it to improve performance
        Tidy availability... 	OK
Starting bokken, running on:
  Python version:
    2.7.16rc1 (default, Feb 18 2019, 11:05:09) 
    [GCC 8.2.0]
  GTK version: 2.24.32
  PyGTK version: 2.24.0

Traceback (most recent call last):
  File "./bokken.py", line 31, in <module>
    import ui.main as main
  File "/root/Downloads/bokken-master/ui/main.py", line 44, in <module>
    import ui.textviews as textviews
  File "/root/Downloads/bokken-master/ui/textviews.py", line 35, in <module>
    import ui.bindiff as bindiff
  File "/root/Downloads/bokken-master/ui/bindiff.py", line 25, in <module>
    from r2.r_core import *
ImportError: dynamic module does not define init function (initr_core)

Thank you in advance <3

**Comment by radare** [comment]
i dont think bokken is maintained anymore, and this seems to be an issue with python, not bokken. I would recommend you to switch to Cutter

**Comment by Maijin** [comment]
https://cutter.re/

**Comment by nohope91** [comment]
WOW O_O
Interesting !!!!
thanks for replying so fast ^_^
you can close the issue :D

**Comment by radare** [comment]
Btw the real repo is in https://github.com/inguma/bokken, open the issue there if u care about fixing the issue in bokken :)
